### ISSUE TITLE
make sure every language uploads test results from a separate folder

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#308]
This prevents the issue where language outputs get comingled and cause spurious failures. Should something like this:
```
steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: java_artifacts
      - name: Publish Test Report - Java
        uses: EnricoMi/publish-unit-test-result-action@v1.23
        with:
          files: 'java_artifacts/**/*.xml'
          check_name: Java Test Report
```
